"""add avatar-icon

Revision ID: 1000c47244af
Revises: 98e458a4fcc9
Create Date: 2016-10-09 09:42:46.066309

"""

# revision identifiers, used by Alembic.
revision = '1000c47244af'
down_revision = '98e458a4fcc9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
