"""initial migration

Revision ID: 2bd35ad0dd79
Revises: None
Create Date: 2016-10-07 21:28:31.485975

"""

# revision identifiers, used by Alembic.
revision = '2bd35ad0dd79'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    ### end Alembic commands ###
